theme: jekyll-theme-minimal
title: Nikko Pante
show_downloads: false
logo: docs/assets/logo.jpg
description: My career began with Python automation that sparked interest to data science. Joining STAMINA4Space opened the door to geospatial data, leading me to build geospatial web applications.